### ISSUE TITLE
Create a basic front end

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tool/opt-out#1]
The browser extension is continually working in the background. When Twitter loads:

    Find the relevant element where the tweets are
    Access the tweets
    Send them back the API
    If it returns 1: replace the tweet with a cat emoji, else: do nothing

Let's make it fancier once this is done

**Comment by Jolg42** [comment]
So what should the extension do?

- Run when a twitter page is loaded
- Get the content of each tweet and call the API to get the score
- Based on the score, do something?

This something could maybe be:
- If score is bad
	- Remove the whole tweet?
	- Hide tweet / make it visible on mouseover?
	- Replace the text with something else?
- If score is good
	- Nothing?
	- Add a ✅?

**Comment by MikeJohnPage** [comment]
Can this be extensible to any web page by searching the _all_ elements of the tree for any offensive text?

Having just inspected some tweets (and finding the relevant class) I think not, but will be interested to hear from somebody with more experience.

**Comment by malteserteresa** [comment]
Done :)
