### ISSUE TITLE
Deploy an online version

### ISSUE THREAD

**Issue by Jolg42** [opt-out-tool/opt-out#17]
What are the options?

- AWS
- Digital Ocean
- Heroku
- Azure
	- https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-train-tensorflow
	- https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-deploy-and-where
- [FloydHub](https://www.floydhub.com/)
- Google Cloud https://cloud.google.com/ml-engine/docs/tensorflow/deploying-models

If it can be free, without maintenance and could be deployed easily from the GitHub repo it would be great I think.

**Comment by malteserteresa** [comment]
Also I'm not sure how to ship this? Or docker?

**Comment by Jolg42** [comment]
I'll try Docker as it will be easy to create an instance an any machine and deploy it on cloud / VM.

**Comment by malteserteresa** [comment]
That would be so helpful thank you!

**Comment by Jolg42** [comment]
Here is a Docker setup
https://github.com/opt-out-tool/opt-out/pull/29

The next step will be to deploy the Docker image somewhere!
