### ISSUE TITLE
Connect extension with api

### ISSUE THREAD

**Issue by linahanner** [opt-out-tool/opt-out#7]
As a user we want to be able to receive a Sentiment evaluation. Since the evaluation is done by the API we need to find a way for the Firefox Extension to communicate with the API.

The route for the Sentiment evaluation is through the **GET** request to **/predict** which takes the query parameter **sentence** in which you send in the text/sentence you want to evaluate.

**Comment by linahanner** [comment]
The absolute easiest implementation of this would be to send a hard-coded value to the API and as a response is received print it to the browser console. Once this is done we have established initial communication between the extension and api and could extend upon it.

Not having any experience with Firefox Extension I am not entirely sure how this would be done, and if someone might have an idea or would like to pitch in I would love the feedback!

**Comment by malteserteresa** [comment]
Hi Lina, I've sent you a link to slack from opt.out.tool@gmail.com, check your spam!

**Comment by malteserteresa** [comment]
Once the front-end is built, this will no longer be an issue
